Jjdzr7 t1 18
infoshareacademy/jjdzr7-4M-D pull request #16
Opened 2022-10-29 09:50 UTC by michal-dziedzic

metoda zwracająca koszt przepisu - metoda costCalculator dodaje ceny produktów

    przesłoniecie metody toString - zrobione
    dodanie oceny (od 0 do 5) - dodane w construktorze i setterze (jeżeli wprowadzimy niepoprawną liczbe, wyswietli sie komunikat w terminalu)
    zwrócenie średniej ocen - zrobione
    wygenerowanie listy składników względem porcji - zrobione jako kopia obiektu  z klasy Recipe i dopiero wtedy obliczona
    obliczenie kosztu na podstawie porcji - zrobione jako kopia obiektu  z klasy Recipe i dopiero wtedy obliczona

2022-11-01 15:13 UTC, Gregory784 approved these changes

2022-11-06 17:41 UTC, mikolka9144 requested changes

2022-11-06 17:41 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/domain/Recipe.java
> +    private void checkPoints(List<Integer> ratings) {
kod do poprawy (proponuje użycie enuma dla zapisu ocen)

2022-11-06 18:41 UTC, mikolka9144 approved these changes

2022-11-06 18:43 UTC, merged