Jjdzr7 t1 20
infoshareacademy/jjdzr7-4M-D pull request #20
Opened 2022-11-06 19:26 UTC by michal-dziedzic

2022-11-10 23:24 UTC, mikolka9144 requested changes

2022-11-10 23:24 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/Application.java
> +
Czyżby pozostałe importy po testach? ;)

2022-11-10 23:24 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/models/Planner.java
> +package com.infoshareacademy.four_md.models;
Przenieś tą klasę do model/Planner.java ( jak wykonasz "git merge main" na swojego brancha, to zobaczysz, o czym mówię)

2022-11-13 12:37 UTC, michalwozniak86 approved these changes

2022-11-20 15:49 UTC, Gregory784 approved these changes

2022-11-20 17:45 UTC, mikolka9144 approved these changes

2022-11-20 17:46 UTC, merged