4 users added to repository Users
infoshareacademy/jjdzr7-4M-D pull request #22
Opened 2022-11-20 10:22 UTC by michal-dziedzic

2022-11-20 17:57 UTC, mikolka9144 requested changes

2022-11-20 17:57 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/models/User.java
>      private String name;
Uzgodnij implementacje User-a z Danielem

2022-11-20 17:57 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/repository/Users.java
> +
NIe udostępniasz możliwości modyfikacji usera (no bo jak zamierzasz stworzyć tego pierwszego użytkownika?)
\# rekomenduje odziedziczyć tu po FileHandler i np. nadpisać getAll() <- getUsers()

2022-11-27 09:37 UTC, mikolka9144 commented
Twoja funkcjonalność znajdywała się już w aplikacji + U standaryzowałem klasy do zapisu danych (https://github.com/infoshareacademy/jjdzr7-4M-D/pull/25), z tego powodu zamykam ten pull request

2022-11-27 09:37 UTC, closed without merging

2022-11-27 13:03 UTC, michal-dziedzic commented
Hej Mikołaj, miałem w Jira taki opis zadania:
"stworzyć plik w resources, który pod uruchomieniu app doda przykładowych userów do pamięci - użyć fileHandlera, który jest w projekcie"
Czy w (https://github.com/infoshareacademy/jjdzr7-4M-D/pull/25) też jest takie repo z przykladowymi userami? 
Bo nie  mogę tego znaleść i jeszcze jakbyś mógł poprawić, użytkownicy zapisywali się w resources przy tworzeniu.
(src/main/resources/users/).

2022-11-27 13:15 UTC, michal-dziedzic commented
W senise chodzi mi czy tell pull request nie powinien zostać, ewentualnie przerobić metode importUsers() po Tych Twoich nowych modyfikacjach?

2022-11-27 13:54 UTC, mikolka9144 commented
> W senise chodzi mi czy tell pull request nie powinien zostać, ewentualnie przerobić metode importUsers() po Tych Twoich nowych modyfikacjach?

Ale FileHandler ma możliwość importowania użytkowników. co do reszty:
- Jeżeli tobie zależy na tworzeniu testowych użytkowników, to możesz napisać test w FileJsonNativeTest (oczywiście domyślnie wyłączony, aby nie zapychać niepotrzebnie bazy)