Jjdzr7 t1 23
infoshareacademy/jjdzr7-4M-D pull request #23
Opened 2022-11-20 17:28 UTC by DanielPopielski

2022-11-20 18:31 UTC, mikolka9144 requested changes
Kilka małych rzeczy do poprawy. :)

2022-11-20 18:31 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/models/User.java
> +package com.infoshareacademy.four_md.models;
Main posiada klasę User (nie ma potrzeby jej nadpisywania)

2022-11-20 18:31 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/model/BookCook.java
> +        return dataUser;
a co to za potworek jest.
Jeżeli chcesz zaimplementować tekstową reprezentacje klasy, to nadpisz toString()

2023-01-22 18:21 UTC, DanielPopielski reviewed
Sprawdźcie czy nic się nie pomieszało.

2023-03-02 23:18 UTC, closed without merging