Jjdzr7 t1 32
infoshareacademy/jjdzr7-4M-D pull request #28
Opened 2023-02-10 14:33 UTC by michal-dziedzic

2023-02-19 18:49 UTC, mikolka9144 requested changes
Generalnie widoki spoko. Przydalby sie jakis controller do zmapowania tego.

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Duplikat odniesienia do spring-web

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/resources/templates/add-recipe.html
> +                        <input type="number" step="any" class="form-control" required th:placeholder="'Cost'"
this shouldn't accept negative numbers in view

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/model/dto/Recipe.java
> +    private String method;
Niejasna nazwa (to jest sposb przygotowania, czy metoda HTTP?)

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/model/dto/Recipe.java
>      private String name;
name akceptuje puste nazwy wprowadzone z formulaza pomimt tagu NotEmpty (moze  warto ja zrobic na stronie)

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/model/dto/Recipe.java
> +    private String method;
method akceptuje puste nazwy wprowadzone z formulaza pomimo  tagu NotEmpty (moze  warto ja zrobic na stronie)

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/java/com/infoshareacademy/four_md/model/dto/Recipe.java
>      private int calories;
Kiedy z interfejsu wprowadzi sie wartosci po kropce (co sie da) to strona zuca brzydki blad: Failed to convert property value of type java.lang.String to required type int for property estimatedCookingTime; nested exception is java.lang.NumberFormatException: For input string: "-1.5"

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/resources/templates/add-recipe.html
> +                    <a class="btn btn-outline-primary" role="button" id="btn2">+ Add new Ingredient</a>
Jezeli dajesz mozliwosc dodawadia dodatkowych przepisow, to moze daj tez mozliwosc ich usuwania ?!?

2023-02-19 18:49 UTC, mikolka9144 commented on 4MD/src/main/resources/templates/add-recipe.html
> +                '                    <label class="form-label">Name</label>\n' +
Wzorowe pole do przyjmowania nazwy (teraz zrob tak wszystkie)

2023-02-26 10:38 UTC, mikolka9144 requested changes
Spoko kod, tylo wymaga niewielkich poprawek

2023-02-26 10:38 UTC, mikolka9144 commented on 4MD/src/main/resources/templates/add-recipe.html
> +                <input class="form-control" type="text" placeholder="Name" th:field="*{name}">
To przepisy nie muszą mieć nazw?

2023-02-26 10:38 UTC, mikolka9144 commented on 4MD/src/main/resources/templates/add-recipe.html
> +    <title>Ex 8</title>
Czemu formularz do dodawania przepisów nazywa się 'Ex 8'

2023-02-26 18:17 UTC, michalwozniak86 approved these changes

2023-02-26 18:48 UTC, mikolka9144 approved these changes

2023-02-26 18:49 UTC, merged