first commit
infoshareacademy/jjdzr7-4M-D pull request #5
Opened 2022-09-04 17:40 UTC by michalwozniak86

Please check it out

2022-09-04 18:18 UTC, michal-dziedzic approved these changes

2022-09-11 16:43 UTC, mikolka9144 requested changes

2022-09-11 16:43 UTC, mikolka9144 commented on 4MD_console/src/main/java/com/infoshareacademy/Score.java
> +        recipe = getRecipe();
getRecipe nie zadziała bez przypisanego Recipe. Może lepiej pobrać Recipe z konstruktora?

2022-09-15 19:57 UTC, mikolka9144 approved these changes

2022-09-15 20:19 UTC, merged